package com.switchfully.jaws.services.security;

public enum Feature {
    CREATE_PARKING_LOT,
    GET_DIVISION_OVERVIEW,
    CREATE_DIVISION,
    REGISTER_MEMBER,
    CREATE_SUBDIVISION,
    GET_PARKING_LOT_OVERVIEW,
    GET_MEMBER_OVERVIEW,
    SELECT_MEMBERSHIP,
    CREATE_ALLOCATION_PARKING_SPOT,
    STOP_ALLOCATION_PARKING_SPOT,
    GET_PARKING_ALLOCATION_OVERVIEW
}
